/// <reference types="vite/client" />
// Auto-generated by `wrangler types` — do not edit manually.
// Run `npm run types` to regenerate after wrangler.toml changes.
// Note: NO top-level import statements here — they would make this a module
// and break the global `Env` declaration. Use inline import() instead.

interface Env {
  // Durable Object — name must match class name for routeAgentRequest routing
  ChatAgent: DurableObjectNamespace<import("./src/chat").ChatAgent>;
  // R2 bucket
  SPECS_BUCKET: R2Bucket;
  // CF Workers AI binding
  AI: Ai;
  // Rate limit binding (per-IP cap on /translate + chat surfaces)
  RATE_LIMIT: { limit(opts: { key: string }): Promise<{ success: boolean }> };
  // Per-feature model selection (wrangler.toml [vars]) — split so /translate
  // and chat can run on different models with different cost profiles.
  QUICK_CF_MODEL_TRANSLATE: string;
  QUICK_CF_MODEL_CHAT: string;
  // "workers-ai" (default) | "anthropic" | "openai-agents" | "vercel"
  QUICK_AI_BACKEND?: string;
  // Secrets (wrangler secret put)
  ANTHROPIC_API_KEY?: string;
  QUICK_CLAUDE_MODEL?: string;
  OPENAI_API_KEY?: string;
}
