/// <reference types="vite/client" />
// Auto-generated by `wrangler types` — do not edit manually.
// Run `npm run types` to regenerate after wrangler.toml changes.
// Note: NO top-level import statements here — they would make this a module
// and break the global `Env` declaration. Use inline import() instead.

interface Env {
  // Durable Object — name must match class name for routeAgentRequest routing
  PipelineAgent: DurableObjectNamespace;
  // Container — Typst PDF compiler (quick-tool serve inside Docker).
  // Name MUST be lowercase (Docker image tag constraint).
  // [[durable_objects.bindings]] exposes the DO namespace in env;
  // [[containers]] (same name) makes it container-aware (ctx.container populated).
  typst_compiler: DurableObjectNamespace<import("./src/compiler").TypstCompiler>;
  // R2 bucket
  SPECS_BUCKET: R2Bucket;
  // CF Workers AI binding
  AI: Ai;
  // Variables (wrangler.toml [vars])
  QUICK_CF_MODEL: string;
  // "workers-ai" (default) | "anthropic" | "openai-agents" | "vercel"
  QUICK_AI_BACKEND?: string;
  // Secrets (wrangler secret put)
  ANTHROPIC_API_KEY?: string;
  QUICK_CLAUDE_MODEL?: string;
  OPENAI_API_KEY?: string;
}
