// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /translate`.
 */
export type TranslateRequest = { 
/**
 * EN construction-spec markdown to translate.
 */
content: string, };
