// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /translate`.
 */
export type TranslateRequest = { content: string, 
/**
 * Optional — `"spec"` (default) for markdown specs, `"label"` for SVG labels.
 */
mode: string | null, };
