// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Success response from `POST /translate`.
 */
export type TranslateResponse = { 
/**
 * Translated Thai markdown.
 */
thai: string, };
