#!/usr/bin/env nu

# data/paint.nu — generates specs/_partials/paint-quantity-<scope>.md from data/*.json.
#
# Run via `mise run gen` (or `quick-tool gen`). Idempotent per the project
# rule: a second run with no input change writes zero files.
#
# Each scope has a list of `surfaces` (each with a name + area_m2) and a list
# of `products` (paint catalog IDs). For each product the script computes:
#   cans = ceil(total_area × default_coats / coverage_m2_per_can_per_coat)
#   cost = cans × baht_per_can
#
# Emits one partial per paint scope under specs/_partials/paint-quantity-*.md
# at heading level ### so it nests cleanly inside a spec's `## ` section.

def main [] {
  let data_dir = ($env.QUICK_DATA_DIR? | default "data")
  let specs_dir = ($env.QUICK_SPECS_DIR? | default "specs")
  let partials_dir = $"($specs_dir)/_partials"

  let paints = (open $"($data_dir)/paints.json" | get paints)
  let scopes = (open $"($data_dir)/scope-picks.json" | get paints)

  mut wrote = 0
  mut skipped = 0

  for scope_id in ($scopes | columns) {
    let scope = ($scopes | get $scope_id)
    let md = (gen_scope_md $scope $paints)
    let out = $"($partials_dir)/paint-quantity-($scope_id).md"

    let existing = (try { open --raw $out } catch { "" })
    if $existing == $md {
      $skipped += 1
    } else {
      $md | save --force --raw $out
      print $"  wrote ($out)"
      $wrote += 1
    }
  }

  print $"gen-paint: ($wrote) written, ($skipped) skipped"
}

def gen_scope_md [scope paints] {
  let total_area = ($scope.surfaces | get area_m2 | math sum | math round --precision 3)

  # Surface-area table
  let surface_header = [
    "| Surface | Area \(m²\) |"
    "|---|---|"
  ]
  let surface_body = ($scope.surfaces | each {|s|
    $"| ($s.name) | ($s.area_m2) |"
  })
  let surface_total = $"| **Total** | **($total_area)** |"
  let surface_table = ($surface_header ++ $surface_body ++ [$surface_total]) | str join "\n"

  # Per-product calc rows
  let product_rows = ($scope.products | each {|pid|
    let p = ($paints | get $pid)
    let coats = $p.default_coats
    let coverage = $p.coverage_m2_per_can_per_coat
    let effective = ($coverage / $coats)
    let cans = (($total_area * $coats / $coverage) | math ceil)
    let cost = ($cans * $p.baht_per_can | into int)
    {
      name: $p.name
      sku: $p.sku
      url: $p.url
      coverage: $coverage
      coats: $coats
      effective: ($effective | math round --precision 2)
      cans: $cans
      cost: $cost
    }
  })

  let total_cans = ($product_rows | get cans | math sum)
  let total_cost = ($product_rows | get cost | math sum | into int)

  let product_header = [
    "| Product | Coverage | Coats | Effective | Cans | Subtotal |"
    "|---|---|---|---|---|---|"
  ]
  let product_body = ($product_rows | each {|r|
    $"| ($r.name) \(HomePro [($r.sku)]\(($r.url)\)\) | ($r.coverage) m²/can/coat | ($r.coats) | ($r.effective) m²/can | **($r.cans)** | ฿($r.cost) |"
  })
  let product_total = $"| **Total** | | | | **($total_cans) cans** | **฿($total_cost)** |"
  let product_table = ($product_header ++ $product_body ++ [$product_total]) | str join "\n"

  let frontmatter = $"---
title: ($scope.title)
status: Draft
rev: \"1\"
generated: true
---

"

  let header = $"### ($scope.title)

"

  let footer = "

*Generated by `data/paint.nu` from `data/*.json` — do not edit this file by hand; change the JSON and run `mise run gen`.*
"

  $frontmatter + $header + $surface_table + "\n\n" + $product_table + $footer
}
