#!/usr/bin/env nu

# data/tiles.nu — generates specs/_partials/tile-quantity-<scope>.md from data/*.json.
#
# Run via `mise run gen` (or `quick-tool gen` once the Rust wrapper lands).
#
# Idempotent per the project rule: a second run with no input change writes
# zero files. Hash-and-skip on each output.
#
# Each scope is rendered as one unified per-surface table — floor surfaces
# (from rooms[]) + optional wall surfaces (from wall_surfaces[]) sit in the
# same table with a "Type" column distinguishing them.

def main [] {
  let data_dir = ($env.QUICK_DATA_DIR? | default "data")
  let specs_dir = ($env.QUICK_SPECS_DIR? | default "specs")
  let partials_dir = $"($specs_dir)/_partials"

  let tiles = (open $"($data_dir)/tiles.json" | get tiles)
  let rooms = (open $"($data_dir)/rooms.json" | get rooms)
  let scopes = (open $"($data_dir)/scope-picks.json" | get scopes)

  mut wrote = 0
  mut skipped = 0

  for scope_id in ($scopes | columns) {
    let scope = ($scopes | get $scope_id)
    let tile = ($tiles | get $scope.tile_id)
    let md = (gen_scope_md $scope $tile $rooms)
    let out = $"($partials_dir)/tile-quantity-($scope_id).md"

    let existing = (try { open --raw $out } catch { "" })
    if $existing == $md {
      $skipped += 1
    } else {
      $md | save --force --raw $out
      print $"  wrote ($out)"
      $wrote += 1
    }
  }

  print $"gen-tiles: ($wrote) written, ($skipped) skipped"
}

# Generate the markdown body for one scope.
def gen_scope_md [scope tile rooms] {
  let tile_area_m2 = (($tile.size_w_mm * $tile.size_h_mm) / 1000000.0)
  let waste_factor = (1.0 + ($scope.wastage_pct / 100.0))

  # Floor surfaces — from scope.rooms (each room is a floor)
  let floor_surfaces = ($scope.rooms | each {|rid|
    let r = ($rooms | get $rid)
    let area = ($r.width_m * $r.length_m)
    {
      name: $r.name
      kind: "Floor"
      dim_label: $"($r.width_m) × ($r.length_m) m"
      area: ($area | math round --precision 3)
    }
  })

  # Wall surfaces — optional. Default to empty list if the scope doesn't list any.
  let wall_surfaces_raw = ($scope | get -o wall_surfaces | default [])
  let wall_surfaces = ($wall_surfaces_raw | each {|w|
    let area = ($w.w_m * $w.h_m)
    {
      name: $w.name
      kind: "Wall"
      dim_label: $"($w.w_m) × ($w.h_m) m"
      area: ($area | math round --precision 3)
    }
  })

  let surfaces = ($floor_surfaces ++ $wall_surfaces)

  let total_area = ($surfaces | get area | math sum | math round --precision 3)
  let tiles_with_waste = (($total_area / $tile_area_m2) * $waste_factor | math ceil)

  # Pricing — three cases in priority order
  let has_box = ($tile.tiles_per_box != null and $tile.baht_per_box != null)
  let boxes = if $has_box { (($tiles_with_waste / $tile.tiles_per_box) | math ceil) } else { 0 }

  let cost = if $has_box {
    ($boxes * $tile.baht_per_box | into int)
  } else if ($tile.baht_per_tile != null) {
    ($tiles_with_waste * $tile.baht_per_tile | math round | into int)
  } else if ($tile.baht_per_m2 != null) {
    ($total_area * $waste_factor * $tile.baht_per_m2 | math round | into int)
  } else { 0 }

  let url_line = if $tile.url != null {
    $"Source: [($tile.supplier)]\(($tile.url)\)"
  } else {
    $"Source: ($tile.supplier)"
  }

  # Per-surface table
  let header_rows = [
    "| Surface | Type | Dimensions | Area \(m²\) |"
    "|---|---|---|---|"
  ]
  let body_rows = ($surfaces | each {|s|
    $"| ($s.name) | ($s.kind) | ($s.dim_label) | ($s.area) |"
  })
  let total_row = $"| **Total** | | | **($total_area)** |"
  let table = ($header_rows ++ $body_rows ++ [$total_row]) | str join "\n"

  # Math + cost lines
  let math_line = $"Tile: ($tile.size_w_mm) × ($tile.size_h_mm) mm \(($tile_area_m2 | math round --precision 3) m² each\). Wastage: ($scope.wastage_pct) %.\n\nTiles needed: **($tiles_with_waste)**."

  let cost_line = if $has_box {
    $"\n\nBoxes to buy: **($boxes)** × ฿($tile.baht_per_box)/box = **฿($cost)**"
  } else if $cost > 0 {
    $"\n\n**Tile subtotal: ฿($cost)**"
  } else { "" }

  let frontmatter = $"---
title: ($scope.title)
status: Draft
rev: \"1\"
generated: true
---

"

  let header = $"## ($scope.title)

Tile: **($tile.name)** — ($tile.slip_rating), ($tile.finish)

($url_line)

"

  let footer = "

*Generated by `data/tiles.nu` from `data/*.json` — do not edit this file by hand; change the JSON and run `mise run gen`.*
"

  $frontmatter + $header + $table + "\n\n" + $math_line + $cost_line + $footer
}
