#!/usr/bin/env nu

# data/windows.nu — generates specs/_partials/window-quantity-<scope>.md
# from data/windows.json + data/scope-picks.json.
#
# Each scope has a list of `items` (each with a window_id, qty, label,
# opening size). For each item the script computes:
#   line_min  = qty × baht_per_unit_min
#   line_max  = qty × baht_per_unit_max
#   line_label = "฿X-Y" if min != max else "฿X"
#
# Total row sums all line_min and line_max separately.
#
# Run via `mise run gen` (or `quick-tool gen`). Idempotent per the
# project rule: a second run with no input change writes zero files.

def main [] {
  let data_dir = ($env.QUICK_DATA_DIR? | default "data")
  let specs_dir = ($env.QUICK_SPECS_DIR? | default "specs")
  let partials_dir = $"($specs_dir)/_partials"

  let windows = (open $"($data_dir)/windows.json" | get windows)
  let scopes = (open $"($data_dir)/scope-picks.json" | get windows)

  mut wrote = 0
  mut skipped = 0

  for scope_id in ($scopes | columns) {
    let scope = ($scopes | get $scope_id)
    let md = (gen_scope_md $scope $windows)
    let out = $"($partials_dir)/window-quantity-($scope_id).md"

    let existing = (try { open --raw $out } catch { "" })
    if $existing == $md {
      $skipped += 1
    } else {
      $md | save --force --raw $out
      print $"  wrote ($out)"
      $wrote += 1
    }
  }

  print $"gen-windows: ($wrote) written, ($skipped) skipped"
}

def gen_scope_md [scope windows] {
  # Per-item rows with computed line totals
  let item_rows = ($scope.items | each {|item|
    let w = ($windows | get $item.window_id)
    let line_min = ($item.qty * $w.baht_per_unit_min | into int)
    let line_max = ($item.qty * $w.baht_per_unit_max | into int)
    let unit_price = (price_label $w.baht_per_unit_min $w.baht_per_unit_max)
    let line_total = (price_label $line_min $line_max)
    {
      label: $item.label
      opening: $item.opening_size_cm
      product_name: $w.name
      sku: $w.sku
      url: $w.url
      frame_size: $"($w.size_w_cm) × ($w.size_h_cm) cm"
      stock_or_custom: $w.stock_or_custom
      qty: $item.qty
      unit_price: $unit_price
      line_min: $line_min
      line_max: $line_max
      line_total: $line_total
    }
  })

  let total_qty = ($item_rows | get qty | math sum)
  let total_min = ($item_rows | get line_min | math sum | into int)
  let total_max = ($item_rows | get line_max | math sum | into int)
  let total_label = (price_label $total_min $total_max)

  # Item table
  let header = [
    "| Item | Opening | Frame size | Type | Qty | Unit price | Line total |"
    "|---|---|---|---|---|---|---|"
  ]
  let body = ($item_rows | each {|r|
    let link = if $r.url != null and $r.sku != null {
      $"[($r.product_name)]\(($r.url)\) \(SKU ($r.sku)\)"
    } else if $r.url != null {
      $"[($r.product_name)]\(($r.url)\) \(custom\)"
    } else {
      $"($r.product_name) \(custom\)"
    }
    $"| ($r.label) | ($r.opening) | ($r.frame_size) | ($link) | ($r.qty) | ($r.unit_price) | ($r.line_total) |"
  })
  let total_row = $"| **Total** | | | | **($total_qty)** | | **($total_label)** |"
  let table = ($header ++ $body ++ [$total_row]) | str join "\n"

  let frontmatter = $"---
title: ($scope.title)
status: Draft
rev: \"1\"
generated: true
---

"

  let header_md = $"### ($scope.title)

"

  let footer = "

*Generated by `data/windows.nu` from `data/*.json` — do not edit this file by hand; change the JSON and run `mise run gen`.*
"

  $frontmatter + $header_md + $table + $footer
}

# Format a price as a range "฿X-Y" if min != max, else "฿X".
def price_label [min max] {
  if $min == $max {
    $"฿($min)"
  } else {
    $"฿($min)-($max)"
  }
}
